# -*- coding: utf-8 -*-
"""ACD-Net.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CDZLOBBFGHhO1qrDESpWezgfpgYzNuOs

# ACD-Net for ASD Classification

This notebook implements the proposed Adaptive Channel-Aware Deep Learning Network (ACD-Net) for Autism Spectrum Disorder classification using rs-fMRI functional connectivity matrices.

Dataset:
- ABIDE PCP
- CC200 Atlas

Input:
- Precomputed 200×200 functional connectivity matrices

Output:
- ASD vs Typical Control classification
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, roc_auc_score, classification_report, f1_score,
)

from tensorflow.keras.models import Model
from tensorflow.keras.layers import (
    Input, Conv2D, MaxPooling2D, Flatten, Dense, Dropout,
    Multiply, GlobalAveragePooling2D, Reshape
)
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

# ===== 1. Load the Data =====
X = connectomes  # Shape: (samples, 200, 200)
X = X.reshape(-1, 200, 200, 1)
print(f"Loaded data: X shape = {X.shape}, y shape = {y.shape}")

# ===== 2. Train-Test Split =====
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# ===== 3. Attention Mechanism =====
def attention_block(inputs):
    channels = inputs.shape[-1]

    gap = GlobalAveragePooling2D(name='attention_gap')(inputs)

    attention_weights = Dense(
        channels,
        activation='sigmoid',
        name='attention_weights'
    )(gap)

    scale = Multiply()([
        inputs,
        Reshape((1,1,channels))(attention_weights)
    ])

    return scale

# ===== 4. CNN + Attention Model =====
def build_cnn_attention(input_shape):
    input_layer = Input(shape=input_shape)

    x = Conv2D(32, (3,3), activation='relu', padding='same')(input_layer)
    x = MaxPooling2D((2,2))(x)

    x = Conv2D(64, (3,3), activation='relu', padding='same')(x)
    x = MaxPooling2D((2,2))(x)

    x = Conv2D(128, (3,3), activation='relu', padding='same')(x)
    x = MaxPooling2D((2,2))(x)

    x = attention_block(x)

    x = Flatten()(x)
    x = Dense(128, activation='relu')(x)
    x = Dropout(0.5)(x)

    output = Dense(1, activation='sigmoid')(x)

    model = Model(inputs=input_layer, outputs=output)
    model.compile(
        optimizer=Adam(learning_rate=0.0001),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )
    return model

model = build_cnn_attention((200, 200, 1))
model.summary()

# ===== 5. Train Model =====
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

history = model.fit(
    X_train, y_train,
    validation_split=0.1,
    epochs=50,
    batch_size=32,
    callbacks=[early_stop],
    verbose=2
)

# ===== 6. Evaluate Model =====
y_pred_prob = model.predict(X_test).ravel()
y_pred = (y_pred_prob >= 0.5).astype(int)

accuracy = accuracy_score(y_test, y_pred)
auc_score = roc_auc_score(y_test, y_pred_prob)
f1 = f1_score(y_test, y_pred)

print("\n Evaluation Metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"AUC Score: {auc_score:.4f}")
print(f"F1 Score: {f1:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

#Average Channel Attention Weights
attention_model = Model(
    inputs=model.input,
    outputs=model.get_layer('attention_weights').output
)

weights = attention_model.predict(X_test)
print(weights.shape)
mean_weights = np.mean(weights, axis=0)

plt.figure(figsize=(12,4))
plt.bar(range(128), mean_weights)
plt.xlabel("Channel")
plt.ylabel("Average Attention Weight")
plt.title("Average Channel Attention Weights")
plt.show()